<b><h1>Basic Commands</b></h1>

In [93]:
print("fit a model with", 11, "variables")

fit a model with 11 variables


In [94]:
3+5

8

In [95]:
"hello"+"world"

'helloworld'

In [96]:
# In Python, lists hold arbitrary objects, and are added using concatenation
x=[3,4,5]
y=[5,8,9]
print(x+y)

[3, 4, 5, 5, 8, 9]


<b><h1>NUMPY</h1></b>

In [97]:
import numpy as np

In [98]:
x=np.array([3,4,5])
y=np.array([5,7,8])
x+y
#different from the python addition, here shape must be equal or same 

array([ 8, 11, 13])

In [99]:
#2D arrays 

x = np.array([[1,2,3],[3,4,5],[7,8,9]])
x

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

The object x has several attributes, or associated objects- x.ndim , x,dtype

In [100]:
print(x.ndim)
print(x.dtype)
#2d matrix or array or vector, comprised of 64bit integers

2
int64


In [101]:
#replaced 2 with 2.3
x = np.array([[1,2.3,3],[3,4,5],[7,8,9]])
x.dtype

dtype('float64')

In [102]:
#Access documentation of any function using help() or ?(jupiter environment) after any object of function
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [103]:
#to get the rows and coloumns of a matrix or array
x.shape


(3, 3)

 A method is a function that is associated with an object. For instance, method given an array x, the expression x.sum() sums all of its elements, using the sum() method for arrays. The call x.sum() automatically provides x as the .sum() first argument to its sum() method.

In [104]:
x = np.array([[1,2,3],[3,4,5],[7,8,9]])
x.sum()
#summed up each individual element

np.int64(42)

In [105]:
#alternate method
np.sum(x)

np.int64(42)

In [106]:
# reshape returns a new array and does not modify the orignal one
x = np.array([[1,2,3],[3,4,5],[7,8,9],[2,3,7]])
print("start:\n",x,'\n',x.shape)
y=x.reshape(3,4)
print(y,'\n',y.shape)

#the reshape function can only work when the product of the shapes are equal to the number of elements in the touple

start:
 [[1 2 3]
 [3 4 5]
 [7 8 9]
 [2 3 7]] 
 (4, 3)
[[1 2 3 3]
 [4 5 7 8]
 [9 2 3 7]] 
 (3, 4)


 numpy arrays are specified as a sequence of rows. This is called <b>row-major ordering</b>, in row major ordering elements are filled row1 first then row 2 , as opposed to coloumn major ordering where 1sr column is filled then the 2nd , numpy is ROW major ordering 
 also , pythonuses 0 based indexing that is 1st elemt is at 0th position

In [107]:
print(y)
print(f"first row and first column {y[0,0]}")
print(f"3rd row and 2nd column {y[2,1]}")
print(f"2nd row and 4th column {y[1,3]}")
print(f"accesing row 2 {y[1,:]}")
print(f"accessing column 2 {y[:,1]}")

#: is used to access single columns or rows in numpy

[[1 2 3 3]
 [4 5 7 8]
 [9 2 3 7]]
first row and first column 1
3rd row and 2nd column 2
2nd row and 4th column 8
accesing row 2 [4 5 7 8]
accessing column 2 [2 5 2]


In [ ]:
print(f"Orignal list \n{x}")
print(f"list after reshape \n {y}")
#changing the 1st element of the matrix 0,0
y[0,0]=23
print(f"reshaped list \n {y}")
print(f"orignal list\n{x}")


# although reshape gives us a new array, the new array references the old one , hence changing the new one changes the old or 
# changing the old one changes the new reshaped one


Orignal list 
[[1 2 3]
 [3 4 5]
 [7 8 9]
 [2 3 7]]
list after reshape 
 [[1 2 3 3]
 [4 5 7 8]
 [9 2 3 7]]
reshaped list 
 [[23  2  3  3]
 [ 4  5  7  8]
 [ 9  2  3  7]]
orignal list
[[23  2  3]
 [ 3  4  5]
 [ 7  8  9]
 [ 2  3  7]]


<h2>TUPPLE</h2>above code we saw that the orignal and new reshaped both get changed if even 1 get changed , that is not the case with tupple as <b>they are inherently immutable</b> 