<b><h1>Basic Commands</b></h1>

In [1]:
print("fit a model with", 11, "variables")

fit a model with 11 variables


In [2]:
3+5

8

In [3]:
"hello"+"world"

'helloworld'

In [4]:
# In Python, lists hold arbitrary objects, and are added using concatenation
x=[3,4,5]
y=[5,8,9]
print(x+y)

[3, 4, 5, 5, 8, 9]


<b><h1>NUMPY</h1></b>

In [5]:
import numpy as np

In [6]:
x=np.array([3,4,5])
y=np.array([5,7,8])
x+y
#different from the python addition, here shape must be equal or same 

array([ 8, 11, 13])

In [7]:
#2D arrays 

x = np.array([[1,2,3],[3,4,5],[7,8,9]])
x

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

The object x has several attributes, or associated objects- x.ndim , x,dtype

In [8]:
print(x.ndim)
print(x.dtype)
#2d matrix or array or vector, comprised of 64bit integers

2
int64


In [9]:
#replaced 2 with 2.3
x = np.array([[1,2.3,3],[3,4,5],[7,8,9]])
x.dtype

dtype('float64')

In [10]:
#Access documentation of any function using help() or ?(jupiter environment) after any object of function
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [11]:
#to get the rows and coloumns of a matrix or array
x.shape


(3, 3)

 A method is a function that is associated with an object. For instance, method given an array x, the expression x.sum() sums all of its elements, using the sum() method for arrays. The call x.sum() automatically provides x as the .sum() first argument to its sum() method.

In [12]:
x = np.array([[1,2,3],[3,4,5],[7,8,9]])
x.sum()
#summed up each individual element

np.int64(42)

In [13]:
#alternate method
np.sum(x)

np.int64(42)

In [14]:
# reshape returns a new array and does not modify the orignal one
x = np.array([[1,2,3],[3,4,5],[7,8,9],[2,3,7]])
print("start:\n",x,'\n',x.shape)
y=x.reshape(3,4)
print(y,'\n',y.shape)

#the reshape function can only work when the product of the shapes are equal to the number of elements in the touple

start:
 [[1 2 3]
 [3 4 5]
 [7 8 9]
 [2 3 7]] 
 (4, 3)
[[1 2 3 3]
 [4 5 7 8]
 [9 2 3 7]] 
 (3, 4)


 numpy arrays are specified as a sequence of rows. This is called <b>row-major ordering</b>, in row major ordering elements are filled row1 first then row 2 , as opposed to coloumn major ordering where 1sr column is filled then the 2nd , numpy is ROW major ordering 
 also , pythonuses 0 based indexing that is 1st elemt is at 0th position

In [15]:
print(y)
print(f"first row and first column {y[0,0]}")
print(f"3rd row and 2nd column {y[2,1]}")
print(f"2nd row and 4th column {y[1,3]}")
print(f"accesing row 2 {y[1,:]}")
print(f"accessing column 2 {y[:,1]}")

#: is used to access single columns or rows in numpy

[[1 2 3 3]
 [4 5 7 8]
 [9 2 3 7]]
first row and first column 1
3rd row and 2nd column 2
2nd row and 4th column 8
accesing row 2 [4 5 7 8]
accessing column 2 [2 5 2]


In [16]:
print(f"Orignal list \n{x}")
print(f"list after reshape \n {y}")
#changing the 1st element of the matrix 0,0
y[0,0]=23
print(f"reshaped list \n {y}")
print(f"orignal list\n{x}")


# although reshape gives us a new array, the new array references the old one , hence changing the new one changes the old or 
# changing the old one changes the new reshaped one


Orignal list 
[[1 2 3]
 [3 4 5]
 [7 8 9]
 [2 3 7]]
list after reshape 
 [[1 2 3 3]
 [4 5 7 8]
 [9 2 3 7]]
reshaped list 
 [[23  2  3  3]
 [ 4  5  7  8]
 [ 9  2  3  7]]
orignal list
[[23  2  3]
 [ 3  4  5]
 [ 7  8  9]
 [ 2  3  7]]


<h2>TUPPLE</h2>above code we saw that the orignal and new reshaped both get changed if even 1 get changed , that is not the case with tupple as <b>they are inherently immutable</b> 

In [20]:
Tup1 = (3,4,5)
Tup1[0]=2

TypeError: 'tuple' object does not support item assignment

In [24]:
y,y.shape,y.ndim,y.T, y.T.shape, y.T.ndim

(array([[23,  2,  3,  3],
        [ 4,  5,  7,  8],
        [ 9,  2,  3,  7]]),
 (3, 4),
 2,
 array([[23,  4,  9],
        [ 2,  5,  2],
        [ 3,  7,  3],
        [ 3,  8,  7]]),
 (4, 3),
 2)

In [25]:
np.sqrt(y)

array([[4.79583152, 1.41421356, 1.73205081, 1.73205081],
       [2.        , 2.23606798, 2.64575131, 2.82842712],
       [3.        , 1.41421356, 1.73205081, 2.64575131]])

In [26]:
np.square(y)

array([[529,   4,   9,   9],
       [ 16,  25,  49,  64],
       [ 81,   4,   9,  49]])

In [27]:
np.square(y).T

array([[529,  16,  81],
       [  4,  25,   4],
       [  9,  49,   9],
       [  9,  64,  49]])

In [28]:
y**0.5

array([[4.79583152, 1.41421356, 1.73205081, 1.73205081],
       [2.        , 2.23606798, 2.64575131, 2.82842712],
       [3.        , 1.41421356, 1.73205081, 2.64575131]])

In [29]:
y**2

array([[529,   4,   9,   9],
       [ 16,  25,  49,  64],
       [ 81,   4,   9,  49]])

In [31]:
help(np.random.normal)

Help on method normal in module numpy.random:

normal(loc=0.0, scale=1.0, size=None) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)

    Draw random samples from a normal (Gaussian) distribution.

    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).

    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.

    .. note::
        New code should use the `~numpy.random.Generator.normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    loc : float or array_li

In [35]:
l= np.random.normal(size=50)
#by def loc/mean =0 and std, dev/ scale= 1
l

array([-1.49784896, -1.05844346,  0.74292823, -1.77654044,  0.2363559 ,
       -1.29342155,  1.07248617,  1.09479873, -0.69704265,  0.87291725,
        1.723091  ,  0.66973142, -0.44349115,  0.91518347,  1.00327756,
       -1.02565758, -0.73498879,  0.1271389 , -0.24197097, -0.48125299,
        2.05259635,  0.47456297,  1.54972533, -1.07963518,  0.17184782,
       -0.0330232 , -0.81433092, -0.71320684, -1.99908561,  0.912566  ,
       -0.08237118, -0.17972592, -0.45181563, -0.24691229, -0.46022211,
        0.86676048,  2.36849453,  3.05886458,  0.49991143, -0.66729236,
        0.01246304, -0.39038344, -1.32756904, -0.83055281, -0.20485404,
        0.41239825,  0.33200438, -0.32318948, -0.29156573,  0.44776353])

In [48]:
print(f"max val= {l.max()}\nmin val= {l.min()}\nmean val= {l.mean()}")
print(f"std dev= {l.std()}\nvariance= {l.var()}")
l.shape, l.ndim
#as u see mean is 0 and std dev is 1 as we used default values

max val= 3.0588645846000704
min val= -1.999085608564085
mean val= 0.0454294598716744
std dev= 1.03859649073083
variance= 1.078682670558395


((50,), 1)

In [43]:

m= l + np.random.normal(loc=50, scale=1, size=50)
m

array([49.43380726, 50.25983079, 52.08805277, 47.60765405, 48.85287992,
       46.93447582, 49.35921388, 51.31073078, 49.65757145, 51.36055406,
       52.44248991, 51.03630573, 50.65533526, 51.37139921, 49.90742164,
       47.66142601, 49.61807305, 49.98625517, 50.76791719, 50.05149086,
       53.13146499, 50.42315475, 52.15343871, 49.02464561, 51.37977783,
       49.9771441 , 47.49616896, 51.06261064, 48.3541432 , 50.47308085,
       50.80951147, 49.40042189, 50.44665937, 48.41059736, 49.04443572,
       51.67997365, 52.80351722, 53.57731934, 51.23572937, 49.04800239,
       51.12715644, 50.47644042, 47.49814822, 50.5185515 , 50.89907531,
       50.22231136, 51.2843789 , 50.67670334, 48.91036517, 49.83404021])

In [49]:
help(np.corrcoef)

Help on _ArrayFunctionDispatcher in module numpy:

corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)
    Return Pearson product-moment correlation coefficients.

    Please refer to the documentation for `cov` for more detail.  The
    relationship between the correlation coefficient matrix, `R`, and the
    covariance matrix, `C`, is

    .. math:: R_{ij} = \frac{ C_{ij} } { \sqrt{ C_{ii} C_{jj} } }

    The values of `R` are between -1 and 1, inclusive.

    Parameters
    ----------
    x : array_like
        A 1-D or 2-D array containing multiple variables and observations.
        Each row of `x` represents a variable, and each column a single
        observation of all those variables. Also see `rowvar` below.
    y : array_like, optional
        An additional set of variables and observations. `y` has the same
        shape as `x`.
    rowvar : bool, optional
        If `rowvar` is True (default), then each row represents a
        variable, with 

In [62]:
np.corrcoef(l,m)

array([[1.        , 0.78699363],
       [0.78699363, 1.        ]])

In [66]:
help(np.random.default_rng)
#we use this instead of the normal random generator as it is 
# more flexible and one can generate the same random numbers by setting a seed value

Help on cython_function_or_method in module numpy.random:

default_rng(seed=None)
    default_rng(seed=None)

    Construct a new Generator with the default BitGenerator (PCG64).

    Parameters
    ----------
    seed : {None, int, array_like[ints], SeedSequence, BitGenerator, Generator, RandomState}, optional
        A seed to initialize the `BitGenerator`. If None, then fresh,
        unpredictable entropy will be pulled from the OS. If an ``int`` or
        ``array_like[ints]`` is passed, then all values must be non-negative and will be
        passed to `SeedSequence` to derive the initial `BitGenerator` state. One may also
        pass in a `SeedSequence` instance.
        Additionally, when passed a `BitGenerator`, it will be wrapped by
        `Generator`. If passed a `Generator`, it will be returned unaltered.
        When passed a legacy `RandomState` instance it will be coerced to a `Generator`.

    Returns
    -------
    Generator
        The initialized generator object.

In [67]:
print(np.random.normal(scale=5, size=2))

print(np.random.normal(scale=5, size=2))

[-6.75022171 -2.59651743]
[-1.9304576  -4.22380734]


In [82]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

#different variables but same seed value gives same random numbers, be sure to keep the scale same

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [90]:
q= np.random.default_rng(3).standard_normal(10)
q, q.mean(), q.std(), q.var(),np.mean(q)

(array([ 2.04091912, -2.55566503,  0.41809885, -0.56776961, -0.45264929,
        -0.21559716, -2.01998613, -0.23193238, -0.86521308,  3.32299952]),
 np.float64(-0.1126795190952861),
 np.float64(1.6505576756498128),
 np.float64(2.7243406406465125),
 np.float64(-0.1126795190952861))

In [99]:
print(f"{np.var(q)}, {q.var()} , {np.mean((q-q.mean())**2)}")

2.7243406406465125, 2.7243406406465125 , 2.7243406406465125


In [100]:
np.sqrt(np.var(q)), np.std(q)

(np.float64(1.6505576756498128), np.float64(1.6505576756498128))